// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czmcecbespcgfzugbayx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6bWNlY2Jlc3BjZ2Z6dWdiYXl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzOTk5MDEsImV4cCI6MjA2OTk3NTkwMX0.sv-5_9NzoqX8ygr0WUMtIBa0UZ1KHut3mJ_jpg7lcoU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});